//
//  ListPresenter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 27.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
    func presentItems(response: [AddToList.DataModel]?)
    func presentItemDetail()
}

final class ListPresenter: ListPresentationLogic {
    weak var viewController: ListDisplayLogic?
    
    func presentItems(response: [AddToList.DataModel]?) {
        
        
        viewController?.displayItems(viewModel: response)
    }
    
    func presentItemDetail() {
        viewController?.displayItemDetail()
    }
}
