//
//  ListRouter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 27.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListRoutingLogic {
    func routeToItemDetail()
}

protocol ListDataPassing {
    var dataStore: ListDataStore? { get }
}

final class ListRouter: NSObject, ListRoutingLogic, ListDataPassing {
    weak var viewController: ListViewController?
    var dataStore: ListDataStore?
    
    // MARK: Routing
    
    func routeToItemDetail() {
        let itemDetailVC = ItemDetailViewController.instantiateFromStoryboard()
        var destinationDS = itemDetailVC.router!.dataStore!
        passDataToItemDetail(source: dataStore!, destination: &destinationDS)
        navigateToItemDetail(source: viewController!, destination: itemDetailVC)
    }
    
    // MARK: Navigation
    
    func navigateToItemDetail(source: ListViewController, destination: ItemDetailViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToItemDetail(source: ListDataStore, destination: inout ItemDetailDataStore) {
        destination.selectedItem = source.selectedItem
    }
}
