//
//  ListInteractor.swift
//  Mowie
//
//  Created by Turan Yilmaz on 27.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBusinessLogic {
    func getItems(for list: ListType, and itemType: ItemType)
    func showItemDetail(selectedItem: ItemDetail.SelectedItem?)

}

protocol ListDataStore {
    var selectedItem: ItemDetail.SelectedItem? { get set }
}

final class ListInteractor: ListBusinessLogic, ListDataStore {
    var presenter: ListPresentationLogic?
    var worker: ListWorker?
    
    var selectedItem: ItemDetail.SelectedItem?
    
    func getItems(for list: ListType, and itemType: ItemType) {
        let items = DatabaseManager.shared.getItems(for: list, and: itemType)
        
        presenter?.presentItems(response: items)
    }
    
    func showItemDetail(selectedItem: ItemDetail.SelectedItem?) {
        self.selectedItem = selectedItem
        presenter?.presentItemDetail()
    }
}
