//
//  ItemDetailWorker.swift
//  Mowie
//
//  Created by Turan Yilmaz on 14.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ItemDetailWorker {
    let itemDetailService: ItemDetailServiceProtocol
    
    init(itemDetailService: ItemDetailServiceProtocol) {
        self.itemDetailService = itemDetailService
    }
    
//    func getMovieDetail(request: ItemDetail.Movie.Request, completion: @escaping (Result<ItemDetail.Movie.Response, APIError>) -> Void) {
//        itemDetailService.getMovieDetail(request: request) { (result) in
//            completion(result)
//        }
//    }
//
//    func getTVDetail(request: ItemDetail.TV.Request, completion: @escaping (Result<ItemDetail.TV.Response, APIError>) -> Void) {
//        itemDetailService.getTVDetail(request: request) { (result) in
//            completion(result)
//        }
//    }
    
//    func getItemDetail(pageType: PageType,
//                       request: ItemDetail.GetItemDetail.BaseItemRequest,
//                       completion: @escaping (ItemDetail.GetItemDetail.BaseItemResponse?, APIError?) -> Void) {
//
//
//        switch pageType {
//        case .movie:
//            itemDetailService.getMovieDetail(request: request) { (result) in
//                switch result {
//                case .success(let response):
//                    completion(response, nil)
//                case .failure(let error):
//                    completion(nil, error)
//                }
//            }
//        case .tv:
//            itemDetailService.getTVDetail(request: request) { (result) in
//                switch result {
//                case .success(let response):
//                    completion(response, nil)
//                case .failure(let error):
//                    completion(nil, error)
//                }
//            }
//        }
//
//
//
//
//
//
//
//    }
    
    
    func getItemDetail(request: ItemDetail.GetItemDetail.BaseItemRequest,
                       completion: @escaping (Result<ItemDetail.GetItemDetail.BaseItemResponse, APIError>) -> Void) {
        itemDetailService.getItemDetail(request: request) { (result) in
            completion(result)
        }
    }
}
