//
//  GenresPresenter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 7.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenresPresentationLogic: BasePresentationLogic {
    func presentGenreList(response: Genres.GetGenres.Response, for type: ItemType)
}

final class GenresPresenter: BasePresenter, GenresPresentationLogic {
    weak var viewController: GenresDisplayLogic?
    
    func presentGenreList(response: Genres.GetGenres.Response, for type: ItemType) {
        let genreList = response.genres.map { (genre) -> Genres.GetGenres.ViewModel in
            
            return Genres.GetGenres.ViewModel(id: genre.id,
                                              name: genre.name,
                                              imageUrl: Utility.getGenreImageUrl(with: genre.id, for: type))
        }
        viewController?.displayGenreList(viewModel: genreList)
    }
}
