//
//  GenresRouter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 7.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GenresRoutingLogic {
    func routeToItems()
}

protocol GenresDataPassing {
    var dataStore: GenresDataStore? { get }
}

final class GenresRouter: NSObject, GenresRoutingLogic, GenresDataPassing {
    weak var viewController: GenresViewController?
    var dataStore: GenresDataStore?
    
    // MARK: Routing
    
    func routeToItems() {
        let itemsVC = ItemsViewController.instantiateFromStoryboard()
        var destinationDS = itemsVC.router!.dataStore!
        passDataToItems(source: dataStore!, destination: &destinationDS)
        navigateToItems(source: viewController!, destination: itemsVC)
    }
    
    // MARK: Navigation
    
    func navigateToItems(source: GenresViewController, destination: ItemsViewController) {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToItems(source: GenresDataStore, destination: inout ItemsDataStore) {
        destination.itemListType = source.itemListType
        destination.title = source.genreName
    }
}
