//
//  GenresInteractor.swift
//  Mowie
//
//  Created by Turan Yilmaz on 7.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenresBusinessLogic: BaseBusinessLogic {
    func getGenres(for type: ItemType)
    func setItemListTypeAndGenreName(type: ItemListType, genreName: String)
}

protocol GenresDataStore {
    var itemListType: ItemListType { get set }
    var genreName: String? { get set }
}

final class GenresInteractor: BaseInteractor, GenresBusinessLogic, GenresDataStore {
    var presenter: GenresPresentationLogic?
    var worker: GenresWorker = GenresWorker(genresService: GenresService())
    
    var itemListType: ItemListType = .movie(.genre(0))
    var genreName: String?
    
    func getGenres(for type: ItemType) {
        
        let request = Genres.GetGenres.Request(genreListType: type)
        
        worker.getGenres(request: request) { (result) in
            switch result {
            case .success(let response):
                self.presenter?.presentGenreList(response: response, for: type)
            case .failure(let error):
                self.showErrorAlert(error: error)
            }
        }
    }
    
    func setItemListTypeAndGenreName(type: ItemListType, genreName: String) {
        self.itemListType = type
        self.genreName = genreName
    }
}
