//
//  GenresModels.swift
//  Mowie
//
//  Created by Turan Yilmaz on 7.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Genres {
    // MARK: Use cases
    
    enum GetGenres {

        struct Request: RequestProtocol {
            var url: URL?
            
            init(genreListType: ItemType) {
                switch genreListType {
                case .movie:
                    url = ServiceURL.movieGenreList.url
                case .tv:
                    url = ServiceURL.tvGenreList.url
                }
            }
        }
        
        struct Response: Codable {
            let genres: [Genre]
        }
        
        struct ViewModel: ListViewModelProtocol {
            let id: Int
            let name: String
            let imageUrl: URL?
        }
    }
    
    struct Genre: Codable {
        let id: Int
        let name: String
    }
}
