//
//  ItemsRouter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 8.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ItemsRoutingLogic {
    func routeToItemDetail()
}

protocol ItemsDataPassing {
    var dataStore: ItemsDataStore? { get }
}

final class ItemsRouter: NSObject, ItemsRoutingLogic, ItemsDataPassing {
    weak var viewController: ItemsViewController?
    var dataStore: ItemsDataStore?
    
    // MARK: Routing
    
    func routeToItemDetail() {
        let itemDetailVC = ItemDetailViewController.instantiateFromStoryboard()
        var destinationDS = itemDetailVC.router!.dataStore!
        passDataToItemDetail(source: dataStore!, destination: &destinationDS)
        navigateToItemDetail(source: viewController!, destination: itemDetailVC)
    }
    
    // MARK: Navigation
    
    func navigateToItemDetail(source: ItemsViewController, destination: ItemDetailViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    // MARK: Passing data
    
    func passDataToItemDetail(source: ItemsDataStore, destination: inout ItemDetailDataStore) {
        destination.selectedItem = source.selectedItem
    }
}
