//
//  ItemsPresenter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 8.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemsPresentationLogic: BasePresentationLogic {
    func presentMovieItems(response: Items.Movie.Response)
    func presentTVItems(response: Items.TV.Response)
    func presentItemDetail()
}

final class ItemsPresenter: BasePresenter, ItemsPresentationLogic {
    weak var viewController: ItemsDisplayLogic?
    
    func presentMovieItems(response: Items.Movie.Response) {
        let movieItems = response.results.map { (movieItem) -> ItemCollectionViewCellModel in
            
            return ItemCollectionViewCellModel(id: movieItem.id,
                                               imageUrl: Utility.createImageUrl(with: movieItem.posterPath),
                                               name: movieItem.title,
                                               rate: movieItem.voteAverage,
                                               year: Utility.getYearFromDateString(string: movieItem.releaseDate.stringValue),
                                               type: .movie)
        }
        
        viewController?.displayItems(viewModel: movieItems)
    }
    
    func presentTVItems(response: Items.TV.Response) {
        let tvItems = response.results.map { (tvItem) -> ItemCollectionViewCellModel in
            return ItemCollectionViewCellModel(id: tvItem.id,
                                               imageUrl: Utility.createImageUrl(with: tvItem.posterPath),
                                               name: tvItem.name,
                                               rate: tvItem.voteAverage,
                                               year: Utility.getYearFromDateString(string: tvItem.firstAirDate.stringValue),
                                               type: .tv)
        }
        
        viewController?.displayItems(viewModel: tvItems)
    }
    
    func presentItemDetail() {
        viewController?.displayItemDetail()
    }
}
