//
//  ItemsWorker.swift
//  Mowie
//
//  Created by Turan Yilmaz on 8.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ItemsWorker {
    
    let itemService: ItemsServiceProtocol
    
    init(itemService: ItemsServiceProtocol) {
        self.itemService = itemService
    }
    
    func getMovieItems(request: Items.Movie.Request, completion: @escaping (Result<Items.Movie.Response, APIError>) -> Void) {
        itemService.getMovieItems(request: request) { (result) in
            completion(result)
        }
    }
    
    func getTVItems(request: Items.TV.Request, completion: @escaping (Result<Items.TV.Response, APIError>) -> Void) {
        itemService.getTVItems(request: request) { (result) in
            completion(result)
        }
    }
}
