//
//  BasePresenter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 29.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BasePresentationLogic {
    func presentErrorAlert(error: APIError)
}

class BasePresenter: BasePresentationLogic {
    weak var baseViewController: BaseDisplayLogic?
    
    func presentErrorAlert(error: APIError) {
        
        let alertController = UIAlertController(title: "Error", message: error.message, preferredStyle: .alert)
        alertController.addAction(UIAlertAction(title: "OK", style: .cancel, handler: nil))
        
        
        baseViewController?.displayErrorAlert(alert: alertController)
    }
    
    
}
