//
//  BaseRouter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 29.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BaseRoutingLogic {
}

protocol BaseDataPassing {
    var dataStore: BaseDataStore? { get }
}

class BaseRouter: NSObject, BaseRoutingLogic, BaseDataPassing {
    weak var viewController: BaseViewController?
    var dataStore: BaseDataStore?
}
