//
//  BaseInteractor.swift
//  Mowie
//
//  Created by Turan Yilmaz on 29.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BaseBusinessLogic {
    func showErrorAlert(error: APIError)
}

protocol BaseDataStore {
}

class BaseInteractor: BaseBusinessLogic, BaseDataStore {
    var basePresenter: BasePresentationLogic?
    var baseWorker: BaseWorker?
    
    func showErrorAlert(error: APIError) {
        basePresenter?.presentErrorAlert(error: error)
    }
    
    
}
