//
//  SearchRouter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 13.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
    func routeToItemDetail()
    func routeToPersonDetail()
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get }
}

final class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
    
    // MARK: Routing
    
    func routeToItemDetail() {
        let itemDetailVC = ItemDetailViewController.instantiateFromStoryboard()
        var destinationDS = itemDetailVC.router!.dataStore!
        passDataToItemDetail(source: dataStore!, destination: &destinationDS)
        navigateToItemDetail(source: viewController!, destination: itemDetailVC)
    }
    
    func routeToPersonDetail() {
        let castDetailVC = CastDetailViewController.instantiateFromStoryboard()
        var destinationDS = castDetailVC.router!.dataStore!
        passDataToCastDetail(source: dataStore!, destination: &destinationDS)
        navigateToCastDetail(source: viewController!, destination: castDetailVC)
    }
    
    //MARK: Navigation
    
    func navigateToItemDetail(source: SearchViewController, destination: ItemDetailViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func navigateToCastDetail(source: SearchViewController, destination: CastDetailViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    //MARK: Passing data
    
    func passDataToItemDetail(source: SearchDataStore, destination: inout ItemDetailDataStore) {
        destination.selectedItem = source.selectedItem
    }
    
    func passDataToCastDetail(source: SearchDataStore, destination: inout CastDetailDataStore) {
        destination.selectedCast = source.selectedCast
    }
}
