//
//  SearchWorker.swift
//  Mowie
//
//  Created by Turan Yilmaz on 13.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchWorker {
    let searchService: SearchServiceProtocol
    
    init(searchService: SearchServiceProtocol) {
        self.searchService = searchService
    }
    
    func getSearchResult<T: RequestProtocol, U: Codable>(request: T,
                         completion: @escaping (Result<U, APIError>) -> Void) {
        
        searchService.getSearchResult(request: request) { (result) in
            completion(result)
        }
    }
}
