//
//  WatchProvidersRouter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 2.09.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WatchProvidersRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol WatchProvidersDataPassing {
    var dataStore: WatchProvidersDataStore? { get }
}

final class WatchProvidersRouter: NSObject, WatchProvidersRoutingLogic, WatchProvidersDataPassing {
    weak var viewController: WatchProvidersViewController?
    var dataStore: WatchProvidersDataStore?
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: WatchProvidersViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: WatchProvidersDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
