//
//  AddToListModels.swift
//  Mowie
//
//  Created by Turan Yilmaz on 24.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddToList {
    // MARK: Use cases
    
    struct DataModel {
        let id: Int?
        let posterPath: String?
        let itemName: String?
        let year: String?
        let rate: Double?
        let type: ItemType
        var selectedList: ListType?
    }
    
    struct ViewModel {
        let viewModel: [ListOptionViewModel]
        let posterImageUrl: URL?
        let itemName: String?
        let drawerTitle: String?
    }
}
