//
//  AddToListRouter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 24.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AddToListRoutingLogic {
    func routeToBack()
}

protocol AddToListDataPassing {
    var dataStore: AddToListDataStore? { get }
}

final class AddToListRouter: NSObject, AddToListRoutingLogic, AddToListDataPassing {
    weak var viewController: AddToListViewController?
    var dataStore: AddToListDataStore?
    
    // MARK: Routing
    
    func routeToBack() {
        viewController!.dismiss(animated: false, completion: nil)
    }
}
