//
//  ListsInteractor.swift
//  Mowie
//
//  Created by Turan Yilmaz on 27.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListsBusinessLogic {
    func showLists()
}

protocol ListsDataStore {
    //var name: String { get set }
}

final class ListsInteractor: ListsBusinessLogic, ListsDataStore {
    var presenter: ListsPresentationLogic?
    var worker: ListsWorker?
    
    func showLists() {
        presenter?.presentLists()
    }
}
