//
//  ListsPresenter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 27.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListsPresentationLogic {
    func presentLists()
}

final class ListsPresenter: ListsPresentationLogic {
    weak var viewController: ListsDisplayLogic?
    
    
    func presentLists() {
        
        let itemModel1 = ListTableViewCellModel(list: .toWatch)
        let itemModel2 = ListTableViewCellModel(list: .watched)
        let itemModel3 = ListTableViewCellModel(list: .favourite)
        
        let viewModel = ListViewModel(sections: [ListViewSection(items: [itemModel1, itemModel2, itemModel3],
                                                                 cell: ListTableViewCell.self,
                                                                 cellHeight: .equally)],
                                      showSeparator: true)
        
        viewController?.displayLists(viewModel: viewModel)
    }
}
