//
//  CastDetailRouter.swift
//  Mowie
//
//  Created by Turan Yilmaz on 22.04.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CastDetailRoutingLogic {
    func routeToItemDetail(selectedItem: ItemDetail.SelectedItem?)
}

protocol CastDetailDataPassing {
    var dataStore: CastDetailDataStore? { get }
}

final class CastDetailRouter: NSObject, CastDetailRoutingLogic, CastDetailDataPassing {
    weak var viewController: CastDetailViewController?
    var dataStore: CastDetailDataStore?
    
    // MARK: Routing
    
    func routeToItemDetail(selectedItem: ItemDetail.SelectedItem?) {
        let itemDetailVC = ItemDetailViewController.instantiateFromStoryboard()
        var destinationDS = itemDetailVC.router!.dataStore!
        destinationDS.selectedItem = selectedItem
        navigateToItemDetail(source: viewController!, destination: itemDetailVC)
    }
    
    func navigateToItemDetail(source: CastDetailViewController, destination: ItemDetailViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
}
