//
//  TrailersInteractor.swift
//  Mowie
//
//  Created by Turan Yilmaz on 23.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TrailersBusinessLogic {
//    func getTrailers()
    func getTrailer()
}

protocol TrailersDataStore {
    var trailers: [Video]? { get set }
}

final class TrailersInteractor: TrailersBusinessLogic, TrailersDataStore {
    var presenter: TrailersPresentationLogic?
    var worker: TrailersWorker?
    
    var trailers: [Video]?
    
    func getTrailer() {
        guard let trailers = trailers else {
            return
        }
        
        presenter?.presentTrailer(trailers: trailers)
    }
}
