//
//  TrailersWorker.swift
//  Mowie
//
//  Created by Turan Yilmaz on 23.08.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TrailersWorker {
    func doSomeWork() {
    }
}
